name: morphometrics
channels:
  - conda-forge
  - andfoy
dependencies:
  - conda-forge::python=3.9
  - andfoy::pyqt
  - conda-forge::matplotlib=3.3.3
  - conda-forge::pandas
  - conda-forge::graph-tool
  - conda-forge::pathlib
  - conda-forge::pip>=20.0.2