name: morphometrics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pymeshlab>=2023.12
  - pyqt
  - matplotlib>=3.8
  - pandas
  - graph-tool
  - pip>=20.0
  # Scientific computing
  - scipy
  - scikit-learn
  - statsmodels
  - numpy
  # Data/IO
  - pyyaml
  - ruamel.yaml
  - click
  - mrcfile
  # Visualization/notebooks
  - jupyter
  - napari
  - magicgui
  - pip:
    - git+https://github.com/vladanl/Pyto.git
    - git+https://github.com/bbarad/pycurv.git
    - git+https://github.com/hemanthkapa/napari-vedo-bridge.git
    - napari-tomoslice
    - napari-timelapse-processor